#!/usr/bin/env python3
"""Build seed.sql for D1 from the Supabase export in ../../exports/.

One-shot migration: 2025 profiles become `people`, 2025 registrations become
`submissions` against the archived `register-2025` form, and the two Cloudflare
KV signups become `signup-2026` submissions. Re-runnable — everything is
INSERT OR REPLACE keyed on the original Supabase UUIDs.
"""

import json
import os
import uuid

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "..")
EXPORTS = os.path.join(ROOT, "exports")
OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "seed.sql")


def q(v):
    """Quote a value as a SQL literal."""
    if v is None or v == "":
        return "NULL"
    if isinstance(v, bool):
        return "1" if v else "0"
    if isinstance(v, (int, float)):
        return str(v)
    return "'" + str(v).replace("'", "''") + "'"


def load(name):
    with open(os.path.join(EXPORTS, name)) as f:
        return json.load(f)


profiles = load("profiles.json")
registrations = load("registrations.json")

# The 2025 form, captured as data so the admin can see exactly what was asked.
REGISTER_2025_FIELDS = [
    {"key": "can_attend_invocation", "label": "Can you attend the Invocation (Opening) Gathering?",
     "help": "Thursday, October 16th at The Riverside.",
     "type": "radio", "options": ["Yes", "No", "Maybe"]},
    {"key": "can_attend_integration", "label": "Can you attend the Integration (Closing) Party?",
     "type": "radio", "options": ["Yes", "No", "Maybe"]},
    {"key": "how_did_you_hear", "label": "How did you hear about COhere?", "type": "text"},
    {"key": "co_creating_interests", "label": "Co-creating COhere", "type": "checkboxes",
     "options": [
         "I would like to host or collaboratively design an event during COhere",
         "I would like to host a community dinner (potluck style) during COhere",
         "I would like to volunteer in supporting an event",
         "I would like to help tell the stories that unfold through writing, photo, or video",
     ]},
    {"key": "additional_notes", "label": "Additional Notes or Comments", "type": "textarea"},
]

SIGNUP_2026_FIELDS = [
    {"key": "language", "label": "Site language at signup", "type": "text"},
]

lines = ["-- Generated by seed-from-supabase.py. Do not edit by hand.", "PRAGMA foreign_keys = ON;", ""]

now = "2026-07-27T00:00:00.000Z"

for slug, title, event, fields, active in [
    ("register-2025", "Register for COhere Boulder 2025", "october2025", REGISTER_2025_FIELDS, 0),
    ("signup-2026", "Stay in the loop — COhere Boulder 2026", "october2026", SIGNUP_2026_FIELDS, 1),
]:
    lines.append(
        "INSERT OR REPLACE INTO forms (slug, title, event, fields, active, created_at, updated_at) VALUES "
        f"({q(slug)}, {q(title)}, {q(event)}, {q(json.dumps(fields))}, {active}, {q(now)}, {q(now)});"
    )
lines.append("")

for p in profiles:
    lines.append(
        "INSERT OR REPLACE INTO people (id, email, name, phone, orgs, subscribed, unsubscribe_token, "
        "source, tags, internal_notes, created_at, updated_at) VALUES ("
        f"{q(p['id'])}, {q(p['email'].strip().lower())}, {q(p['full_name'])}, {q(p['phone_number'])}, "
        f"{q(p['organizations'])}, {1 if p['subscribed'] else 0}, {q(p['unsubscribe_token'])}, "
        f"{q('supabase:' + (p['source'] or 'registration'))}, "
        f"{q('admin' if p['role'] == 'admin' else None)}, NULL, "
        f"{q(p['created_at'])}, {q(p['updated_at'])});"
    )
lines.append("")

by_profile = {p["id"]: p for p in profiles}
for r in registrations:
    if r["profile_id"] not in by_profile:
        continue
    data = {
        "can_attend_invocation": {True: "Yes", False: "No"}.get(r["can_attend_invocation"], "Maybe or unanswered"),
        "can_attend_integration": {True: "Yes", False: "No"}.get(r["can_attend_integration"], "Maybe or unanswered"),
        "how_did_you_hear": r["how_did_you_hear"] or "",
        "co_creating_interests": r["co_creating_interests"] or [],
        "additional_notes": r["additional_notes"] or "",
    }
    lines.append(
        "INSERT OR REPLACE INTO submissions (id, person_id, form_slug, event, data, created_at, updated_at) VALUES ("
        f"{q(r['id'])}, {q(r['profile_id'])}, 'register-2025', {q(r['cohere_event'])}, "
        f"{q(json.dumps(data))}, {q(r['created_at'])}, {q(r['updated_at'])});"
    )
lines.append("")

# The two signups already captured in Cloudflare KV.
KV_SIGNUPS = [
    {"email": "ag@unforced.org", "source": "hero", "language": "en", "signedUpAt": "2026-06-10T05:07:11.908Z"},
    {"email": "bdecorte@verdeterrecompost.com", "source": "hero", "language": "en",
     "signedUpAt": "2026-06-10T19:15:45.353Z"},
]
emails = {p["email"].strip().lower() for p in profiles}
for s in KV_SIGNUPS:
    email = s["email"].strip().lower()
    pid = str(uuid.uuid5(uuid.NAMESPACE_URL, "cohere-kv:" + email))
    if email not in emails:
        lines.append(
            "INSERT OR REPLACE INTO people (id, email, name, phone, orgs, subscribed, unsubscribe_token, "
            "source, tags, internal_notes, created_at, updated_at) VALUES ("
            f"{q(pid)}, {q(email)}, NULL, NULL, NULL, 1, {q(str(uuid.uuid5(uuid.NAMESPACE_URL, 'tok:' + email)))}, "
            f"{q('kv:' + s['source'])}, NULL, NULL, {q(s['signedUpAt'])}, {q(s['signedUpAt'])});"
        )
    lines.append(
        "INSERT OR REPLACE INTO submissions (id, person_id, form_slug, event, data, created_at, updated_at) "
        "SELECT "
        f"{q(str(uuid.uuid5(uuid.NAMESPACE_URL, 'cohere-kv-sub:' + email)))}, id, 'signup-2026', 'october2026', "
        f"{q(json.dumps({'language': s['language'], 'source': s['source']}))}, {q(s['signedUpAt'])}, {q(s['signedUpAt'])} "
        f"FROM people WHERE email = {q(email)};"
    )

with open(OUT, "w") as f:
    f.write("\n".join(lines) + "\n")

print(f"wrote {OUT}: {len(lines)} statements")
